name: CI

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "**"

jobs:
  Validate-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r schemas/requirements.txt
      - run: jsonschema --instance build/recommended.json schemas/schema.json
      - run: jsonschema --instance build/strict.json schemas/schema.json
      - run: jsonschema --instance build/risky.json schemas/schema.json
  Validate-test-vectors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/DataDog/libddwaf
      - run: cd libddwaf && git submodule update --init && mkdir build && cd build && cmake .. && make verify_rule -j4
      - run: ./libddwaf/build/examples/verify_rule rules/*/*.yaml
