name: CI

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "**"

jobs:
  Validate-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r schemas/requirements.txt
      - run: python schemas/validate.py
