name: System tests old versions

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '00 04 * * 2-6'
  pull_request:
    branches: "**"

env:
  REGISTRY: ghcr.io

jobs:
  # Golang
  system-tests-golang: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        weblog-variant: [echo, net-http, gorilla, chi]
        version: [gopkg.in/DataDog/dd-trace-go.v1@v1.34.0]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'DataDog/system-tests'

      - name: Checkout appsec-event-rules
        uses: actions/checkout@v2
        with:
          path: 'appsec-event-rules'

      - name: Load WAF ruleset
        run: cp appsec-event-rules/build/recommended.json binaries/waf_rule_set.json

      - name: Set old tracer version
        run: echo ${{ matrix.version }} > binaries/golang-load-from-go-get

      - name: Build
        run: ./build.sh golang -w ${{ matrix.weblog-variant }}

      - name: Run default scenario
        run: ./run.sh
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
  
  # Nodejs
  system-tests-nodejs: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        weblog-variant: [express4]
        version: [dd-trace-js@2.0.0-appsec-alpha.1]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'DataDog/system-tests'

      - name: Checkout appsec-event-rules
        uses: actions/checkout@v2
        with:
          path: 'appsec-event-rules'

      - name: Load WAF ruleset
        run: cp appsec-event-rules/build/recommended.json binaries/waf_rule_set.json

      - name: Set old tracer version
        run: echo ${{ matrix.version }} > binaries/nodejs-load-from-npm

      - name: Build
        run: ./build.sh nodejs -w ${{ matrix.weblog-variant }}

      - name: Run default scenario
        run: ./run.sh
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

  # dotnet
  system-tests-dotnet: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        weblog-variant: [poc]
        version: [datadog-dotnet-apm-1.28.4.tar.gz]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'DataDog/system-tests'

      - name: Checkout appsec-event-rules
        uses: actions/checkout@v2
        with:
          path: 'appsec-event-rules'

      - name: Load WAF ruleset
        run: cp appsec-event-rules/build/recommended.json binaries/waf_rule_set.json

      - name: Set old tracer version
        run: touch binaries/${{ matrix.version }}

      - name: Build
        run: ./build.sh dotnet -w ${{ matrix.weblog-variant }}

      - name: Run default scenario
        run: ./run.sh
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
  # java
  system-tests-java: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        weblog-variant: [spring-boot]
        version: [dd-java-agent-0.86.0.jar]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'DataDog/system-tests'

      - name: Checkout appsec-event-rules
        uses: actions/checkout@v2
        with:
          path: 'appsec-event-rules'

      - name: Load WAF ruleset
        run: cp appsec-event-rules/build/recommended.json binaries/waf_rule_set.json

      - name: Set old tracer version
        run: touch binaries/${{ matrix.version }}

      - name: Build
        run: ./build.sh java -w ${{ matrix.weblog-variant }}

      - name: Run default scenario
        run: ./run.sh
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}